Description of s2let_plot_axisym_tiling
Home > src > main > matlab > s2let_plot_axisym_tiling.m
s2let_plot_axisym_tiling
PURPOSE
plot_axisym_tilling - Plot tilling in harmonic space.
SYNOPSIS
function s2let_plot_axisym_tiling(B, L, J_min)
DESCRIPTION
 plot_axisym_tilling - Plot tilling in harmonic space.
 -- Axisymmetric wavelets on the sphere.
 Default usage :
   plot_axisym_tilling(B, L, J_min)
 B is the wavelet parameter,
 L is the angular band-limit,
 J_min the first wavelet to be used.
 S2LET package to perform Wavelet transform on the Sphere.
 Copyright (C) 2012  Boris Leistedt & Jason McEwen
 See LICENSE.txt for license details
CROSS-REFERENCE INFORMATION
This function calls:
s2let_axisym_tiling s2let_axisym_tiling - Compute tiling in harmonic space.
s2let_jmax s2let_jmax
This function is called by:
s2let_demo2 s2let_demo2
SOURCE CODE
function s2let_plot_axisym_tiling(B, L, J_min)
% plot_axisym_tilling - Plot tilling in harmonic space.
% -- Axisymmetric wavelets on the sphere.
%
% Default usage :
%
%   plot_axisym_tilling(B, L, J_min)
%
% B is the wavelet parameter,
% L is the angular band-limit,
% J_min the first wavelet to be used.
%
% S2LET package to perform Wavelet transform on the Sphere.
% Copyright (C) 2012  Boris Leistedt & Jason McEwen
% See LICENSE.txt for license details
[kappa kappa0] = s2let_axisym_tiling(B, L, J_min);
J = s2let_jmax(L, B);
xi = 0:0.01:L-1;
x = 0:L-1;
figure('Position',[100 100 600 300])
%semilogx(0:L-1, kappa0, 'k', 'LineWidth', 2);
yi = interp1(x,kappa0,xi,'pchip');
semilogx(xi, yi, 'k', 'LineWidth', 2);
h = text(2, 1.07, 'k0', 'Color', [0 0 0]);
hold on;
for j = J_min:J
  colour = rand(1,3)*0.9;
  %plot(0:L-1, kappa(j+1,:), 'LineWidth', 2, 'Color', colour);
    yi = interp1(x,kappa(j+1,:),xi,'pchip');
    semilogx(xi, yi, 'LineWidth', 2, 'Color', colour);
  h = text(B.^j, 1.07, strcat('j',num2str(j+1)), 'Color', colour);
end
%title('Harmonic tiling');
xlabel('el');
axis([0 L -0.05 1.15]);
set(gca,'XTick',2.^[0:(J+2)]);
end