Description of s2let_jmax
Home > src > main > matlab > s2let_jmax.m
s2let_jmax
PURPOSE
s2let_jmax
SYNOPSIS
function J = s2let_jmax(L, B)
DESCRIPTION
 s2let_jmax
 Return the maximum scale for a wavelet transform
 Default usage:
        J_max = s2let_jmax(L, B)
    L is the band-limit for the transform,
    B is the wavelet parameter.
 S2LET package to perform Wavelets transform on the Sphere.
 Copyright (C) 2012-2015  Boris Leistedt & Jason McEwen
 See LICENSE.txt for license details
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
s2let_curvelet_tiling s2let_spin_curvelet_tiling - Tile scaling functions and curvelets in harmonic space.
s2let_curvelet_transform_test_lm2cur_cur2lm s2let_curvelet_transform_test_lm2cur_cur2lm
s2let_curvelet_transform_test_lm2lmn_lmn2lm s2let_curvelet_transform_test_lm2lmn_lmn2lm
s2let_curvelet_transform_test_px2cur_cur2px s2let_curvelet_transform_test_px2cur_cur2px
s2let_demo1 s2let_demo1
s2let_demo2 s2let_demo2
s2let_demo3 s2let_demo3
s2let_demo4 s2let_demo4
s2let_demo5 s2let_demo5
s2let_demo6 s2let_demo6
s2let_demo7_curvelet_Plot_Funcs_and_Tiling s2let_demo7 - plotting curvelets
s2let_demo8_curvelet_Mollweide_EarthTopography s2let_demo8 - curvelet analysis on the Earth topographic map
s2let_demo_covariance s2let_demo_covariance - Run covariance demo.
s2let_demo_curvelet_covariance s2let_demo_curvelet_covariance
s2let_demo_ridgelet_plot s2let_demo_ridgelet_plot
s2let_fulltest s2let_fulltest
s2let_fulltest_curvelet s2let_fulltest_curvelet
s2let_hpxtest s2let_hpxtest
s2let_plot_axisym_tiling plot_axisym_tiling - Plot tiling in harmonic space.
s2let_plot_curvelet_on_sphere s2let_plot_curvelet_on_sphere
s2let_plot_curvelet_parametric s2let_plot_curvelet_parametric
s2let_plot_curvelet_tiling s2let_plot_curvelet_tiling
s2let_plot_mollweide s2let_plot_mollweide
s2let_plot_sphere s2let_plot_sphere
s2let_plot_wavs s2let_plot_wavs
s2let_ridgelet_compute_wav s2let_ridgelet_compute_wav - Compute ridgelets
s2let_transform_analysis_lm2wav s2let_transform_analysis_lm2wav
s2let_transform_analysis_mw s2let_transform_analysis_mw
s2let_transform_axisym_analysis_hpx s2let_transform_axisym_analysis_hpx
s2let_transform_axisym_analysis_mw s2let_transform_axisym_analysis_mw
s2let_transform_axisym_synthesis_hpx s2let_axisym_synthesis
s2let_transform_axisym_synthesis_mw s2let_transform_axisym_synthesis_mw
s2let_transform_curvelet_analysis_lm2cur s2let_transform_curvelet_analysis_lm2cur
s2let_transform_curvelet_analysis_lm2lmn s2let_transform_curvelet_analysis_lm2lmn
s2let_transform_curvelet_analysis_px2cur s2let_transform_curvelet_analysis_px2cur
s2let_transform_curvelet_synthesis_cur2lm s2let_transform_curvelet_synthesis_cur2lm
s2let_transform_curvelet_synthesis_cur2px s2let_transform_curvelet_synthesis_cur2px
s2let_transform_curvelet_synthesis_lmn2lm s2let_transform_curvelet_synthesis_lmn2lm
s2let_transform_synthesis_lm2wav s2let_transform_synthesis_lm2wav
s2let_transform_synthesis_mw s2let_transform_synthesis_mw
SOURCE CODE
function J = s2let_jmax(L, B)
% s2let_jmax
% Return the maximum scale for a wavelet transform
%
% Default usage:
%        J_max = s2let_jmax(L, B)
%
%    L is the band-limit for the transform,
%    B is the wavelet parameter.
%
% S2LET package to perform Wavelets transform on the Sphere.
% Copyright (C) 2012-2015  Boris Leistedt & Jason McEwen
% See LICENSE.txt for license details
J = s2let_jmax_mex(L, B);
end