Description of s2let_mwss_vec2arr
Home > src > main > matlab > s2let_mwss_vec2arr.m
s2let_mwss_vec2arr
PURPOSE
SYNOPSIS
function arr = s2let_mwss_vec2arr(vec)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
s2let_mwss_read_real_map s2let_mw_read_real_map
s2let_transform_analysis_lm2wav s2let_transform_analysis_lm2wav
s2let_transform_analysis_mw s2let_transform_analysis_mw
s2let_transform_synthesis_mw s2let_transform_synthesis_mw
SOURCE CODE
function arr = s2let_mwss_vec2arr(vec)
len = length(vec(:));
delta = sqrt(1 + 2*len);
L = (delta - 1) / 2;
arr = zeros(L+1, 2*L);
for t = 1:L+1
    for p = 1:2*L
        arr(t,p) = vec((t-1)*2*L+p);
    end
end
end