Description of s2let_bandlimit
Home > src > main > matlab > s2let_bandlimit.m
s2let_bandlimit
PURPOSE
s2let_bandlimit
SYNOPSIS
function bl = s2let_bandlimit(j, J_min, B, L)
DESCRIPTION
 s2let_bandlimit
 Return the band-limit of a specific wavelet scale j
 Default usage:
        bl = s2let_bandlimit(j, J_min, B, L)
   j the scale of interest,
   J_min the minimal wavelet scale,
    B is the wavelet parameter,
    L is the band-limit for the transform.
 S2LET package to perform Wavelets transform on the Sphere.
 Copyright (C) 2012-2015  Boris Leistedt & Jason McEwen
 See LICENSE.txt for license details
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
s2let_demo1 s2let_demo1
s2let_demo4 s2let_demo4
s2let_demo6 s2let_demo6
s2let_demo8_curvelet_Mollweide_EarthTopography s2let_demo8 - curvelet analysis on the Earth topographic map
s2let_plot_mollweide s2let_plot_mollweide
s2let_plot_sphere s2let_plot_sphere
s2let_transform_analysis_lm2wav s2let_transform_analysis_lm2wav
s2let_transform_analysis_mw s2let_transform_analysis_mw
s2let_transform_axisym_analysis_mw s2let_transform_axisym_analysis_mw
s2let_transform_axisym_synthesis_mw s2let_transform_axisym_synthesis_mw
s2let_transform_curvelet_analysis_lm2cur s2let_transform_curvelet_analysis_lm2cur
s2let_transform_curvelet_analysis_lm2lmn s2let_transform_curvelet_analysis_lm2lmn
s2let_transform_curvelet_synthesis_cur2lm s2let_transform_curvelet_synthesis_cur2lm
s2let_transform_curvelet_synthesis_lmn2lm s2let_transform_curvelet_synthesis_lmn2lm
s2let_transform_synthesis_lm2wav s2let_transform_synthesis_lm2wav
s2let_transform_synthesis_mw s2let_transform_synthesis_mw
SOURCE CODE
function bl = s2let_bandlimit(j, J_min, B, L)
% s2let_bandlimit
% Return the band-limit of a specific wavelet scale j
%
% Default usage:
%        bl = s2let_bandlimit(j, J_min, B, L)
%
%   j the scale of interest,
%   J_min the minimal wavelet scale,
%    B is the wavelet parameter,
%    L is the band-limit for the transform.
%
% S2LET package to perform Wavelets transform on the Sphere.
% Copyright (C) 2012-2015  Boris Leistedt & Jason McEwen
% See LICENSE.txt for license details
bl = s2let_bandlimit_mex(j, J_min, B, L);
end